"""The migration, and the schema as PostgreSQL actually builds it.

Two things live here that cannot be proved anywhere else: that the migration applies,
reverses and reapplies cleanly, and that everything the scan path writes survives a round
trip through real ``jsonb``, real native enum types and the async session the application
uses.
"""

import os
import subprocess
import sys
from collections.abc import AsyncIterator, Iterator
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from decimal import Decimal
from enum import StrEnum
from pathlib import Path
from uuid import uuid4

import psycopg
import pytest
import sqlalchemy
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from alembic import command
from app.contracts import (
    DeclarationField,
    EvidenceAssetType,
    FieldState,
    RuleParameterSnapshot,
    Verdict,
)
from app.core.db import get_session
from app.core.enums import ReviewAction

# Imported from ``models`` and not from ``schema``, for exactly the reason
# ``test_the_metadata_is_not_empty`` states: ``schema`` defines the base, ``models``
# is what puts tables on it.
from app.core.models import (
    Base,
    CalibrationMethod,
    EvidenceEntryRow,
    FieldFindingRow,
    Scan,
    ScanSourceType,
    ScanStatus,
    VerdictRow,
)
from tests.core.test_persistence import RULE_SET_VERSION, a_finding, a_rule

BCK = Path(__file__).resolve().parents[2]
"""The backend package root, resolved from this file and never from the working
directory — the subprocess below has to start somewhere real."""

JWT_SECRET = "test-signing-key-not-used-anywhere-real"

pytestmark = pytest.mark.postgres

ENUM_TYPES: dict[str, type[StrEnum]] = {
    "calibration_method": CalibrationMethod,
    "declaration_field": DeclarationField,
    "evidence_asset_type": EvidenceAssetType,
    "field_state": FieldState,
    "scan_source_type": ScanSourceType,
    "scan_status": ScanStatus,
    "review_action": ReviewAction,
    "verdict": Verdict,
}
"""Every PostgreSQL enum type this schema creates, against the Python enum behind it."""

ENUM_TYPE_NAMES = set(ENUM_TYPES)

TABLE_NAMES = set(Base.metadata.tables)
"""Every table the schema declares, read from the metadata rather than listed.

Listing them by hand is how a table added to ``models.py`` goes unmigrated and untested at
the same time: the list keeps passing because it never mentioned the new table.
:func:`test_the_metadata_is_not_empty` guards the other direction, because a metadata that
registered nothing would make every assertion about this set vacuously true.
"""

ENUM_TYPES_QUERY = text("select typname from pg_type where typtype = 'e'")

ENUM_LABELS_QUERY = text(
    """
    select t.typname, e.enumlabel
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = any(:names)
    """
)


@pytest.fixture
def migrated(alembic_config: Config) -> Iterator[Config]:
    """A database at head, returned to base afterwards so the next run starts clean."""
    command.upgrade(alembic_config, "head")
    yield alembic_config
    command.downgrade(alembic_config, "base")


def enum_types_and_tables(database_url: str) -> tuple[set[str], set[str]]:
    """What the database actually holds, read back rather than assumed."""
    engine = sqlalchemy.create_engine(database_url)
    try:
        with engine.connect() as connection:
            return set(connection.scalars(ENUM_TYPES_QUERY)), set(
                inspect(connection).get_table_names()
            )
    finally:
        engine.dispose()


def test_the_migration_downgrades_and_reapplies(alembic_config: Config, database_url: str) -> None:
    """upgrade, downgrade, upgrade — the cycle that catches a leftover enum type.

    ``create_table`` creates the six enum types implicitly and autogenerate writes no
    ``DROP TYPE`` for any of them. A downgrade that left them behind would make this
    second upgrade fail with ``type "scan_source_type" already exists`` — one command
    after the one that actually caused it.
    """
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    types, tables = enum_types_and_tables(database_url)
    assert not types & ENUM_TYPE_NAMES
    assert not tables & TABLE_NAMES

    command.upgrade(alembic_config, "head")

    types, tables = enum_types_and_tables(database_url)
    assert types >= ENUM_TYPE_NAMES
    assert tables >= TABLE_NAMES

    command.downgrade(alembic_config, "base")


def test_the_metadata_registers_every_table() -> None:
    """``Base.metadata`` holds the tables, so the assertions below are not vacuous.

    This proves that importing ``app.core.models`` registers the schema — nothing more.

    It was written to prove something stronger and does not: that ``alembic/env.py`` must
    import ``Base`` from ``models`` rather than from ``schema``. That turns out not to be
    a failure mode at all. Importing ``app.core.schema`` executes ``app/core/__init__.py``
    first, which imports ``models``, so the metadata is populated by either path and no
    test can be made to fail on the difference. The claim is corrected here rather than
    the code changed to suit it.
    """
    assert len(Base.metadata.tables) >= 5, (
        f"Base.metadata holds only {sorted(Base.metadata.tables)}. Every assertion about "
        f"the schema below is vacuous when this is empty."
    )
    assert "reviews" in Base.metadata.tables


def test_alembic_sees_the_schema_in_a_fresh_interpreter(
    migrated: Config, database_url: str
) -> None:
    """Run ``alembic check`` in a subprocess, the way a deployment actually runs it.

    :func:`test_the_models_and_the_migration_do_not_disagree` calls ``command.check`` in
    this process, where every model module has already been imported by the test suite. A
    deployment runs the command with a fresh interpreter that imports only what
    ``alembic/env.py`` names, so this runs it that way: a model whose module never gets
    imported by ``env.py`` is invisible to autogenerate there and visible here, and the
    in-process check would stay green while migrations quietly stopped covering it.

    Fails on ordinary drift too — a column added to a model with no migration written for
    it — which is what it was falsified against.
    """
    completed = subprocess.run(
        [sys.executable, "-m", "alembic", "check"],
        cwd=BCK,
        env={**os.environ, "DATABASE_URL": database_url, "JWT_SECRET": JWT_SECRET},
        capture_output=True,
        text=True,
    )
    assert completed.returncode == 0, (
        "`alembic check` failed in a fresh interpreter, which is how a deployment runs "
        f"it:\n{completed.stdout}\n{completed.stderr}"
    )


def test_every_declared_table_reaches_the_database(migrated: Config, database_url: str) -> None:
    """After ``upgrade head``, every table the metadata declares exists for real.

    ``alembic check`` compares the database against the metadata it was handed, so it
    cannot notice that it was handed the wrong metadata. This compares the metadata
    against the database instead, which is the direction that catches a table declared in
    ``models.py`` and never migrated.
    """
    _types, tables = enum_types_and_tables(database_url)
    missing = TABLE_NAMES - tables
    assert not missing, f"declared but absent from the database after upgrade head: {missing}"


def test_the_models_and_the_migration_do_not_disagree(migrated: Config) -> None:
    """``alembic check``: a model edited without a migration is drift, and this catches it.

    Cheap now and load-bearing from the next ticket on, since PIP-002 touches these
    models.
    """
    command.check(migrated)


def test_alembic_check_is_capable_of_reporting_drift(migrated: Config, database_url: str) -> None:
    """Guards the guard above, which would look identical if it compared nothing.

    Drops a column behind Alembic's back and confirms ``check`` notices.
    """
    engine = sqlalchemy.create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(text("alter table scans drop column capture_metadata"))
    engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(migrated)


def a_scan_row(scan_id: uuid4, **overrides: object) -> Scan:
    """A complete scan row. Callers override only what they are testing."""
    fields: dict[str, object] = {
        "id": scan_id,
        "source_type": ScanSourceType.PHYSICAL_LABEL,
        "status": ScanStatus.RECEIVED,
        "calibration_method": CalibrationMethod.NONE,
        "state": "Maharashtra",
        "region": "Pune",
        "district": "Satara",
        "officer_id": "inspector",
        "rule_set_version": RULE_SET_VERSION,
        "image_refs": [],
        "capture_metadata": {},
    }
    fields.update(overrides)
    return Scan(**fields)


@asynccontextmanager
async def request_session() -> AsyncIterator[AsyncSession]:
    """One session, obtained and released exactly as a request handler obtains it.

    ``get_session`` is a generator dependency: FastAPI advances it once and closes it
    when the response is done. Driving it the same way here means its teardown is under
    test too, not just the session it yields.
    """
    sessions = get_session()
    session = await anext(sessions)
    try:
        yield session
    finally:
        await sessions.aclose()


async def test_a_finding_round_trips_through_the_async_session(
    migrated: Config, engine_disposed: None
) -> None:
    """The real path: async session, ``jsonb`` columns, native enum types.

    Everything storage could plausibly damage is in here at once — INSUFFICIENT_EVIDENCE,
    a ``Decimal`` tolerance nested inside the rule snapshot, a nested JSON document, and
    a timezone-aware instant.
    """
    scan_id, verdict_id = uuid4(), uuid4()
    evaluated_at = datetime(2026, 9, 6, 9, 30, tzinfo=UTC)
    snapshot = RuleParameterSnapshot.from_rule(a_rule(), RULE_SET_VERSION)

    async with request_session() as session:
        session.add(
            a_scan_row(
                scan_id,
                source_type=ScanSourceType.CATALOGUE_RECORD,
                status=ScanStatus.COMPLETE,
                capture_metadata={"platform": "test-harness", "nested": {"depth": 2}},
            )
        )
        await session.flush()
        session.add(
            VerdictRow(
                id=verdict_id,
                scan_id=scan_id,
                verdict=Verdict.REVIEW,
                subject_ref=str(scan_id),
                rule_set_version=RULE_SET_VERSION,
                evaluated_at=evaluated_at,
                field_providers={DeclarationField.NET_QUANTITY.value: "PADDLEOCR"},
            )
        )
        await session.flush()
        session.add(
            FieldFindingRow(
                verdict_id=verdict_id,
                field=DeclarationField.NET_QUANTITY,
                rule_id=snapshot.rule_id,
                state=FieldState.INSUFFICIENT_EVIDENCE,
                reason="the net quantity panel was not legible in this capture",
                rule_snapshot=snapshot.model_dump(mode="json"),
                evidence_span_ids=["span-1", "span-2"],
                evidence_regions=[{"polygon": [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0]]}],
            )
        )
        await session.commit()

    async with request_session() as session:
        finding = (await session.scalars(select(FieldFindingRow))).one()
        verdict = (await session.scalars(select(VerdictRow))).one()
        scan = (await session.scalars(select(Scan))).one()

        assert finding.state is FieldState.INSUFFICIENT_EVIDENCE
        assert verdict.verdict is Verdict.REVIEW
        assert scan.source_type is ScanSourceType.CATALOGUE_RECORD

        reloaded = RuleParameterSnapshot.model_validate(finding.rule_snapshot)
        assert reloaded == snapshot
        # The denormalisation's whole basis: the column is a copy of one field of the
        # document beside it, and querying by it is only sound while the two agree.
        assert finding.rule_id == reloaded.rule_id
        assert isinstance(reloaded.tolerance, Decimal)
        assert reloaded.tolerance == Decimal("0.05")

        assert scan.capture_metadata["nested"] == {"depth": 2}
        assert finding.evidence_regions[0]["polygon"][2] == [1.0, 1.0]
        assert verdict.evaluated_at == evaluated_at
        assert verdict.evaluated_at.utcoffset() is not None


async def test_the_enum_type_refuses_a_state_outside_the_five(
    migrated: Config, engine_disposed: None
) -> None:
    """The database's own guard, which exists only because the column is a native type.

    A ``VARCHAR`` here would accept whatever a caller happened to send. The expected
    error is specifically an invalid *value* for the type: if the type had never been
    created at all, the cast would still fail — with ``UndefinedObject`` — and a test
    that only asked for a ``DBAPIError`` would pass without proving anything.
    """
    async with request_session() as session:
        with pytest.raises(sqlalchemy.exc.DBAPIError) as refused:
            await session.execute(text("select 'PROBABLY_FINE'::field_state"))
        assert isinstance(refused.value.orig, psycopg.errors.InvalidTextRepresentation)
        await session.rollback()


async def test_the_chain_cannot_take_two_entries_at_one_sequence(
    migrated: Config, engine_disposed: None
) -> None:
    """The unique constraint, as the storage-level answer to an inserted entry."""
    scan_id = uuid4()

    def an_entry(entry_hash: str) -> EvidenceEntryRow:
        return EvidenceEntryRow(
            id=uuid4(),
            scan_id=scan_id,
            sequence=0,
            timestamp="2026-09-06T09:00:00+00:00",
            payload_hash="0" * 64,
            prev_hash="0" * 64,
            entry_hash=entry_hash,
            payload_json="{}",
            asset_type=EvidenceAssetType.AUDIT_LOG,
        )

    async with request_session() as session:
        session.add(a_scan_row(scan_id))
        await session.flush()
        session.add(an_entry("a" * 64))
        await session.commit()

        session.add(an_entry("b" * 64))
        with pytest.raises(sqlalchemy.exc.IntegrityError):
            await session.commit()
        await session.rollback()


async def test_a_declaration_cannot_be_recorded_twice_against_one_rule(
    migrated: Config, engine_disposed: None
) -> None:
    """``(verdict_id, field, rule_id)`` is unique; ``(verdict_id, field)`` is not.

    One declaration evaluated against several rules is several findings and must stay
    that way. The same declaration recorded twice against the *same* rule is a duplicate,
    and only the third column makes that statable at all — inside the snapshot document
    ``rule_id`` can carry no constraint.
    """
    scan = a_scan_row(uuid4())
    async with request_session() as session:
        session.add(scan)
        await session.flush()
        verdict = VerdictRow(
            id=uuid4(),
            scan_id=scan.id,
            verdict=Verdict.REVIEW,
            subject_ref=str(scan.id),
            rule_set_version=RULE_SET_VERSION,
            evaluated_at=datetime(2026, 9, 6, 9, 0, tzinfo=UTC),
            field_providers={},
        )
        session.add(verdict)
        await session.flush()

        # Same declaration, two different rules: permitted, and the point of the column.
        session.add(a_finding(verdict, FieldState.FAIL, "TEST-RULE-A"))
        session.add(a_finding(verdict, FieldState.PASS, "TEST-RULE-B"))
        await session.commit()

        # Same declaration, same rule, a second time: refused by the database.
        session.add(a_finding(verdict, FieldState.PASS, "TEST-RULE-A"))
        with pytest.raises(sqlalchemy.exc.IntegrityError):
            await session.commit()
        await session.rollback()


def test_every_enum_type_holds_exactly_its_python_members(
    migrated: Config, database_url: str
) -> None:
    """The drift ``alembic check`` cannot see.

    Autogenerate compares tables and columns, not the *values* of an enum type that
    already exists. Add a member to ``contracts.DeclarationField`` and ``alembic check``
    stays clean; the failure surfaces later as ``invalid input value for enum
    declaration_field`` at the first insert that uses it. PIP-002 touches every
    declaration field, so this is a live risk rather than a hypothetical one.

    Reading the labels back out of ``pg_enum`` is the only way to catch it, and it has to
    run against a real database — which is why it lives here rather than beside the
    portable tests.
    """
    engine = sqlalchemy.create_engine(database_url)
    try:
        with engine.connect() as connection:
            rows = connection.execute(ENUM_LABELS_QUERY, {"names": sorted(ENUM_TYPE_NAMES)}).all()
    finally:
        engine.dispose()

    in_database: dict[str, set[str]] = {name: set() for name in ENUM_TYPE_NAMES}
    for type_name, label in rows:
        in_database[type_name].add(label)

    in_python = {name: {member.value for member in enum} for name, enum in ENUM_TYPES.items()}
    assert in_database == in_python
