"""The migration, and the schema as PostgreSQL actually builds it.

Two things live here that cannot be proved anywhere else: that the migration applies,
reverses and reapplies cleanly, and that everything the scan path writes survives a round
trip through real ``jsonb``, real native enum types and the async session the application
uses.
"""

from collections.abc import AsyncIterator, Iterator
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from decimal import Decimal
from uuid import uuid4

import psycopg
import pytest
import sqlalchemy
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from alembic import command
from app.contracts import DeclarationField, FieldState, RuleParameterSnapshot, Verdict
from app.core.db import get_session
from app.core.models import (
    CalibrationMethod,
    EvidenceEntryRow,
    FieldFindingRow,
    Scan,
    ScanSourceType,
    ScanStatus,
    VerdictRow,
)
from tests.core.test_persistence import RULE_SET_VERSION, a_rule

pytestmark = pytest.mark.postgres

ENUM_TYPE_NAMES = {
    "calibration_method",
    "declaration_field",
    "field_state",
    "scan_source_type",
    "scan_status",
    "verdict",
}

TABLE_NAMES = {"scans", "verdicts", "field_findings", "evidence_entries"}

ENUM_TYPES_QUERY = text("select typname from pg_type where typtype = 'e'")


@pytest.fixture
def migrated(alembic_config: Config) -> Iterator[Config]:
    """A database at head, returned to base afterwards so the next run starts clean."""
    command.upgrade(alembic_config, "head")
    yield alembic_config
    command.downgrade(alembic_config, "base")


def enum_types_and_tables(database_url: str) -> tuple[set[str], set[str]]:
    """What the database actually holds, read back rather than assumed."""
    engine = sqlalchemy.create_engine(database_url)
    try:
        with engine.connect() as connection:
            return set(connection.scalars(ENUM_TYPES_QUERY)), set(
                inspect(connection).get_table_names()
            )
    finally:
        engine.dispose()


def test_the_migration_downgrades_and_reapplies(alembic_config: Config, database_url: str) -> None:
    """upgrade, downgrade, upgrade — the cycle that catches a leftover enum type.

    ``create_table`` creates the six enum types implicitly and autogenerate writes no
    ``DROP TYPE`` for any of them. A downgrade that left them behind would make this
    second upgrade fail with ``type "scan_source_type" already exists`` — one command
    after the one that actually caused it.
    """
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    types, tables = enum_types_and_tables(database_url)
    assert not types & ENUM_TYPE_NAMES
    assert not tables & TABLE_NAMES

    command.upgrade(alembic_config, "head")

    types, tables = enum_types_and_tables(database_url)
    assert types >= ENUM_TYPE_NAMES
    assert tables >= TABLE_NAMES

    command.downgrade(alembic_config, "base")


def test_the_models_and_the_migration_do_not_disagree(migrated: Config) -> None:
    """``alembic check``: a model edited without a migration is drift, and this catches it.

    Cheap now and load-bearing from the next ticket on, since PIP-002 touches these
    models.
    """
    command.check(migrated)


def test_alembic_check_is_capable_of_reporting_drift(migrated: Config, database_url: str) -> None:
    """Guards the guard above, which would look identical if it compared nothing.

    Drops a column behind Alembic's back and confirms ``check`` notices.
    """
    engine = sqlalchemy.create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(text("alter table scans drop column capture_metadata"))
    engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(migrated)


def a_scan_row(scan_id: uuid4, **overrides: object) -> Scan:
    """A complete scan row. Callers override only what they are testing."""
    fields: dict[str, object] = {
        "id": scan_id,
        "source_type": ScanSourceType.PHYSICAL_LABEL,
        "status": ScanStatus.RECEIVED,
        "calibration_method": CalibrationMethod.NONE,
        "state": "Maharashtra",
        "region": "Pune",
        "district": "Satara",
        "officer_id": "inspector",
        "rule_set_version": RULE_SET_VERSION,
        "image_refs": [],
        "capture_metadata": {},
    }
    fields.update(overrides)
    return Scan(**fields)


@asynccontextmanager
async def request_session() -> AsyncIterator[AsyncSession]:
    """One session, obtained and released exactly as a request handler obtains it.

    ``get_session`` is a generator dependency: FastAPI advances it once and closes it
    when the response is done. Driving it the same way here means its teardown is under
    test too, not just the session it yields.
    """
    sessions = get_session()
    session = await anext(sessions)
    try:
        yield session
    finally:
        await sessions.aclose()


async def test_a_finding_round_trips_through_the_async_session(
    migrated: Config, engine_disposed: None
) -> None:
    """The real path: async session, ``jsonb`` columns, native enum types.

    Everything storage could plausibly damage is in here at once — INSUFFICIENT_EVIDENCE,
    a ``Decimal`` tolerance nested inside the rule snapshot, a nested JSON document, and
    a timezone-aware instant.
    """
    scan_id, verdict_id = uuid4(), uuid4()
    evaluated_at = datetime(2026, 9, 6, 9, 30, tzinfo=UTC)
    snapshot = RuleParameterSnapshot.from_rule(a_rule(), RULE_SET_VERSION)

    async with request_session() as session:
        session.add(
            a_scan_row(
                scan_id,
                source_type=ScanSourceType.CATALOGUE_RECORD,
                status=ScanStatus.COMPLETE,
                capture_metadata={"platform": "test-harness", "nested": {"depth": 2}},
            )
        )
        await session.flush()
        session.add(
            VerdictRow(
                id=verdict_id,
                scan_id=scan_id,
                verdict=Verdict.REVIEW,
                subject_ref=str(scan_id),
                rule_set_version=RULE_SET_VERSION,
                evaluated_at=evaluated_at,
                field_providers={DeclarationField.NET_QUANTITY.value: "PADDLEOCR"},
            )
        )
        await session.flush()
        session.add(
            FieldFindingRow(
                verdict_id=verdict_id,
                field=DeclarationField.NET_QUANTITY,
                state=FieldState.INSUFFICIENT_EVIDENCE,
                reason="the net quantity panel was not legible in this capture",
                rule_snapshot=snapshot.model_dump(mode="json"),
                evidence_span_ids=["span-1", "span-2"],
                evidence_regions=[{"polygon": [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0]]}],
            )
        )
        await session.commit()

    async with request_session() as session:
        finding = (await session.scalars(select(FieldFindingRow))).one()
        verdict = (await session.scalars(select(VerdictRow))).one()
        scan = (await session.scalars(select(Scan))).one()

        assert finding.state is FieldState.INSUFFICIENT_EVIDENCE
        assert verdict.verdict is Verdict.REVIEW
        assert scan.source_type is ScanSourceType.CATALOGUE_RECORD

        reloaded = RuleParameterSnapshot.model_validate(finding.rule_snapshot)
        assert reloaded == snapshot
        assert isinstance(reloaded.tolerance, Decimal)
        assert reloaded.tolerance == Decimal("0.05")

        assert scan.capture_metadata["nested"] == {"depth": 2}
        assert finding.evidence_regions[0]["polygon"][2] == [1.0, 1.0]
        assert verdict.evaluated_at == evaluated_at
        assert verdict.evaluated_at.utcoffset() is not None


async def test_the_enum_type_refuses_a_state_outside_the_five(
    migrated: Config, engine_disposed: None
) -> None:
    """The database's own guard, which exists only because the column is a native type.

    A ``VARCHAR`` here would accept whatever a caller happened to send. The expected
    error is specifically an invalid *value* for the type: if the type had never been
    created at all, the cast would still fail — with ``UndefinedObject`` — and a test
    that only asked for a ``DBAPIError`` would pass without proving anything.
    """
    async with request_session() as session:
        with pytest.raises(sqlalchemy.exc.DBAPIError) as refused:
            await session.execute(text("select 'PROBABLY_FINE'::field_state"))
        assert isinstance(refused.value.orig, psycopg.errors.InvalidTextRepresentation)
        await session.rollback()


async def test_the_chain_cannot_take_two_entries_at_one_sequence(
    migrated: Config, engine_disposed: None
) -> None:
    """The unique constraint, as the storage-level answer to an inserted entry."""
    scan_id = uuid4()

    def an_entry(entry_hash: str) -> EvidenceEntryRow:
        return EvidenceEntryRow(
            id=uuid4(),
            scan_id=scan_id,
            sequence=0,
            timestamp="2026-09-06T09:00:00+00:00",
            payload_hash="0" * 64,
            prev_hash="0" * 64,
            entry_hash=entry_hash,
            payload_json="{}",
        )

    async with request_session() as session:
        session.add(a_scan_row(scan_id))
        await session.flush()
        session.add(an_entry("a" * 64))
        await session.commit()

        session.add(an_entry("b" * 64))
        with pytest.raises(sqlalchemy.exc.IntegrityError):
            await session.commit()
        await session.rollback()
